# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4ac7071f52b4cc1e1ec96827b43df7ca241f9a305f6cd5e65348af0a4dca626b8822b3499a7b167cc5724835e2c1cc2251d3460440c42089ed94f3a261c8aac9

test:
  secret_key_base: 05c53c4b74c40c963a5c8c54d2f9d8f92d39222efa9c876c2171dbe51c039369d6ac89b455174f64546c654970aa668f8de0aa828e2e1da2fb2e42ac958bfa39

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
